#!/usr/bin/env python3

import os
import sys
from subprocess import call
from tempfile import mkstemp

with open('input.txt', 'r') as fin:
    for sentence in fin:
        print('\n' + sentence)

        sys.stdout.flush()

        tempfd, temp = mkstemp()
        with open(temp, 'w') as fout:
            print(sentence, file=fout)

        call(['../client', '-q', '-s', temp])
        os.close(tempfd)
