#!/bin/bash

# Start C&C server for parsing inputs.

pushd ext/candc
./bin/soap_server --server localhost:8888 \
                  --models models/boxer \
                  --candc-printer boxer \
                  > /dev/null 2> /dev/null &

popd

# Start web service.

cd app
./app.py
